import type { AlertRecord } from '../model/alert-triage';

/** Invented rail incidents for visual and interaction review only. */
export const RAIL_ALERTS: readonly AlertRecord[] = [
  {
    id: 'sample-alert-001',
    tenantId: 'tenant-a',
    assetId: 'asset-005',
    assetLabel: 'Diesel locomotive 206',
    assetType: 'Diesel locomotive',
    componentLabel: 'Traction motor',
    title: 'Inspection required',
    summary: 'Sample diagnostic evidence crossed its illustrative band.',
    severity: 'critical',
    state: 'open',
    firstSeen: '2026-10-06T09:06:00Z',
    lastSeen: '2026-10-06T09:06:00Z',
    triggerCondition:
      'Illustrative traction-motor temperature exceeded 90 °C. The triggering observation arrived late.',
    evidence: [
      {
        id: 'sample-evidence-001',
        label: 'Motor temperature',
        value: 104,
        unit: '°C',
        referenceBand: { lower: 40, upper: 90 },
        eventAt: '2026-10-06T08:32:00Z',
        receivedAt: '2026-10-06T09:05:00Z',
        quality: 'suspect',
        freshness: 'stale',
        source: {
          gatewayId: 'sample-gateway-206',
          endpointId: 'sample-can-port-2',
          signalId: 'sample-motor-temperature',
        },
        series: [
          { at: '2026-10-06T07:50:00Z', value: 78 },
          { at: '2026-10-06T08:10:00Z', value: 85 },
          { at: '2026-10-06T08:32:00Z', value: 104 },
          { at: '2026-10-06T09:00:00Z', value: null },
        ],
        note: 'Late receipt and a subsequent gap limit current-condition confidence.',
      },
    ],
    timeline: [
      {
        id: 'sample-timeline-001-trigger',
        at: '2026-10-06T09:06:00Z',
        kind: 'triggered',
        title: 'Example alert opened',
        detail: 'Delayed motor-temperature evidence crossed the sample band.',
      },
      {
        id: 'sample-timeline-001-receipt',
        at: '2026-10-06T09:05:00Z',
        kind: 'observation',
        title: 'Delayed observation received',
        detail: 'Event time was 08:32; receipt time was 09:05.',
      },
      {
        id: 'sample-timeline-001-gap',
        at: '2026-10-06T09:00:00Z',
        kind: 'gap',
        title: 'No newer sample',
        detail: 'The chart leaves the interval after 08:32 unfilled.',
      },
    ],
  },
  {
    id: 'sample-alert-003',
    tenantId: 'tenant-a',
    assetId: 'asset-006',
    assetLabel: 'Yard shunter 08',
    assetType: 'Shunter',
    componentLabel: 'Monitoring gateway',
    title: 'Intermittent telemetry',
    summary: 'Sample observations have gaps in the example timeline.',
    severity: 'attention',
    state: 'open',
    firstSeen: '2026-10-06T09:40:00Z',
    lastSeen: '2026-10-06T09:40:00Z',
    triggerCondition:
      'No observation for the illustrative gateway heartbeat in the expected sample window.',
    evidence: [
      {
        id: 'sample-evidence-003',
        label: 'Gateway heartbeat',
        value: null,
        unit: 'count',
        referenceBand: null,
        eventAt: null,
        receivedAt: null,
        quality: 'unavailable',
        freshness: 'missing',
        source: {
          gatewayId: 'sample-gateway-08',
          endpointId: 'sample-modem',
          signalId: 'sample-heartbeat',
        },
        series: [
          { at: '2026-10-06T09:00:00Z', value: 1 },
          { at: '2026-10-06T09:12:00Z', value: 1 },
          { at: '2026-10-06T09:30:00Z', value: null },
          { at: '2026-10-06T09:40:00Z', value: null },
        ],
        note: 'A missing heartbeat is not evidence that the whole asset is unhealthy.',
      },
    ],
    timeline: [
      {
        id: 'sample-timeline-003-trigger',
        at: '2026-10-06T09:40:00Z',
        kind: 'triggered',
        title: 'Example gap flagged',
        detail: 'The expected heartbeat was absent in the sample window.',
      },
      {
        id: 'sample-timeline-003-gap',
        at: '2026-10-06T09:30:00Z',
        kind: 'gap',
        title: 'Observation gap begins',
        detail: 'No value is inferred for the missing interval.',
      },
      {
        id: 'sample-timeline-003-prior',
        at: '2026-10-06T09:12:00Z',
        kind: 'observation',
        title: 'Last sample heartbeat',
        detail: 'A prior heartbeat does not make the current evidence fresh.',
      },
    ],
  },
  {
    id: 'sample-alert-004',
    tenantId: 'tenant-a',
    assetId: 'asset-004',
    assetLabel: 'Electric locomotive 417',
    assetType: 'Electric locomotive',
    componentLabel: 'Traction inverter',
    title: 'Inverter current excursion',
    summary: 'The illustrative current returned inside the sample band.',
    severity: 'attention',
    state: 'closed',
    firstSeen: '2026-10-06T09:15:00Z',
    lastSeen: '2026-10-06T09:57:00Z',
    triggerCondition:
      'Illustrative inverter current exceeded 100 A before returning to the sample band.',
    evidence: [
      {
        id: 'sample-evidence-004',
        label: 'Inverter current',
        value: 78,
        unit: 'A',
        referenceBand: { lower: 0, upper: 100 },
        eventAt: '2026-10-06T09:57:00Z',
        receivedAt: '2026-10-06T09:57:24Z',
        quality: 'good',
        freshness: 'current',
        source: {
          gatewayId: 'sample-gateway-417',
          endpointId: 'sample-inverter-bus',
          signalId: 'sample-inverter-current',
        },
        series: [
          { at: '2026-10-06T09:10:00Z', value: 96 },
          { at: '2026-10-06T09:15:00Z', value: 112 },
          { at: '2026-10-06T09:35:00Z', value: 103 },
          { at: '2026-10-06T09:57:00Z', value: 78 },
        ],
        note: 'Closed is a sample lifecycle label, not a live safety assertion.',
      },
    ],
    timeline: [
      {
        id: 'sample-timeline-004-clear',
        at: '2026-10-06T09:57:00Z',
        kind: 'cleared',
        title: 'Example condition cleared',
        detail: 'Current returned inside the illustrative band.',
      },
      {
        id: 'sample-timeline-004-trigger',
        at: '2026-10-06T09:15:00Z',
        kind: 'triggered',
        title: 'Example alert opened',
        detail: 'Sample current exceeded 100 A.',
      },
    ],
  },
];
