import type { AlertRecord } from '../model/alert-triage';

/** Invented machine, road, and trailer incidents for visual review only. */
export const SUPPORT_ALERTS: readonly AlertRecord[] = [
  {
    id: 'sample-alert-002',
    tenantId: 'tenant-a',
    assetId: 'asset-001',
    assetLabel: 'Primary machine',
    assetType: 'Machine',
    componentLabel: 'Power system',
    title: 'Power variation',
    summary: 'Sample power readings varied beyond the example range.',
    severity: 'attention',
    state: 'acknowledged',
    firstSeen: '2026-10-06T09:31:00Z',
    lastSeen: '2026-10-06T09:54:00Z',
    triggerCondition:
      'The illustrative power reading exceeded the sample 250 kW upper band.',
    evidence: [
      {
        id: 'sample-evidence-002',
        label: 'Delivered power',
        value: 260,
        unit: 'kW',
        referenceBand: { lower: 100, upper: 250 },
        eventAt: '2026-10-06T09:54:00Z',
        receivedAt: '2026-10-06T09:54:12Z',
        quality: 'good',
        freshness: 'current',
        source: {
          gatewayId: 'sample-gateway-machine-1',
          endpointId: 'sample-power-bus',
          signalId: 'sample-delivered-power',
        },
        series: [
          { at: '2026-10-06T09:20:00Z', value: 212 },
          { at: '2026-10-06T09:31:00Z', value: 256 },
          { at: '2026-10-06T09:42:00Z', value: 242 },
          { at: '2026-10-06T09:54:00Z', value: 260 },
        ],
        note: 'Good quality describes this reading, not a safe asset condition.',
      },
    ],
    timeline: [
      {
        id: 'sample-timeline-002-latest',
        at: '2026-10-06T09:54:00Z',
        kind: 'observation',
        title: 'Latest sample reading',
        detail: 'Delivered power was 260 kW.',
      },
      {
        id: 'sample-timeline-002-ack',
        at: '2026-10-06T09:42:00Z',
        kind: 'acknowledged',
        title: 'Example acknowledgment',
        detail: 'Acknowledged means seen; it does not mean resolved.',
      },
      {
        id: 'sample-timeline-002-trigger',
        at: '2026-10-06T09:31:00Z',
        kind: 'triggered',
        title: 'Example alert opened',
        detail: 'Sample power exceeded the illustrative band.',
      },
    ],
  },
  {
    id: 'sample-alert-005',
    tenantId: 'tenant-a',
    assetId: 'asset-008',
    assetLabel: 'Refrigerated trailer 11',
    assetType: 'Refrigerated trailer',
    componentLabel: 'Refrigeration unit',
    title: 'Freezer observation unavailable',
    summary: 'The sample trailer has no freezer-air observation.',
    severity: 'information',
    state: 'open',
    firstSeen: '2026-10-06T09:22:00Z',
    lastSeen: '2026-10-06T09:22:00Z',
    triggerCondition:
      'No freezer-air observation exists in the illustrative review window.',
    evidence: [
      {
        id: 'sample-evidence-005',
        label: 'Freezer air temperature',
        value: null,
        unit: '°C',
        referenceBand: null,
        eventAt: null,
        receivedAt: null,
        quality: 'unavailable',
        freshness: 'missing',
        source: {
          gatewayId: 'sample-tracker-011',
          endpointId: 'can-reefer',
          signalId: 'freezer.air.temperature',
        },
        series: [
          { at: '2026-10-06T08:00:00Z', value: null },
          { at: '2026-10-06T09:00:00Z', value: null },
          { at: '2026-10-06T10:00:00Z', value: null },
        ],
        note: 'Known source mapping does not imply that a value was observed.',
      },
    ],
    timeline: [
      {
        id: 'sample-timeline-005-trigger',
        at: '2026-10-06T09:22:00Z',
        kind: 'triggered',
        title: 'Missing evidence noted',
        detail: 'No sample freezer-air reading was present.',
      },
      {
        id: 'sample-timeline-005-gap',
        at: '2026-10-06T09:00:00Z',
        kind: 'gap',
        title: 'No sample series',
        detail: 'The chart does not substitute a zero-temperature reading.',
      },
    ],
  },
  {
    id: 'sample-alert-006',
    tenantId: 'tenant-a',
    assetId: 'asset-007',
    assetLabel: 'Service truck 22',
    assetType: 'Service truck',
    componentLabel: 'Electrical system',
    title: 'Battery sensor plausibility',
    summary:
      'The illustrative voltage remains available but its quality is limited.',
    severity: 'information',
    state: 'acknowledged',
    firstSeen: '2026-10-06T09:50:00Z',
    lastSeen: '2026-10-06T09:56:00Z',
    triggerCondition:
      'Variation in the synthetic sensor sequence requires a quality review.',
    evidence: [
      {
        id: 'sample-evidence-006',
        label: 'Battery voltage',
        value: 25.2,
        unit: 'V',
        referenceBand: { lower: 24, upper: 28 },
        eventAt: '2026-10-06T09:54:00Z',
        receivedAt: '2026-10-06T09:54:31Z',
        quality: 'suspect',
        freshness: 'current',
        source: {
          gatewayId: 'sample-tracker-truck-22',
          endpointId: 'sample-aux-input-1',
          signalId: 'sample-battery-voltage',
        },
        series: [
          { at: '2026-10-06T09:30:00Z', value: 25.5 },
          { at: '2026-10-06T09:42:00Z', value: 27.9 },
          { at: '2026-10-06T09:50:00Z', value: 24.1 },
          { at: '2026-10-06T09:54:00Z', value: 25.2 },
        ],
        note: 'A current timestamp does not remove the suspect quality flag.',
      },
    ],
    timeline: [
      {
        id: 'sample-timeline-006-ack',
        at: '2026-10-06T09:56:00Z',
        kind: 'acknowledged',
        title: 'Example acknowledgment',
        detail: 'The sample quality concern remains visible.',
      },
      {
        id: 'sample-timeline-006-latest',
        at: '2026-10-06T09:54:00Z',
        kind: 'observation',
        title: 'Current but suspect reading',
        detail: 'The voltage is inside the band; quality remains suspect.',
      },
      {
        id: 'sample-timeline-006-trigger',
        at: '2026-10-06T09:50:00Z',
        kind: 'triggered',
        title: 'Example quality review opened',
        detail: 'Variation in the sample series was flagged.',
      },
    ],
  },
];
